apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: m24tzs1yr-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/m24tzs1yr-java-quarkus-gitops